version: "3.9"

networks:
  gitea:
    external: false

secrets:
   gitea_db_port:
     file: .env
   gitea_db_name:
     file: .env
   gitea_db_user:
     file: .env
   gitea_db_pass:
     file: .env

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:gitea_db_port
      - GITEA__database__NAME=gitea_db_name
      - GITEA__database__USER=gitea_db_user
      - GITEA__database__PASSWD=gitea_db_pass
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2221:22"
    depends_on:
      - db
    secrets:
      - gitea_db_port
      - gitea_db_name
      - gitea_db_user
      - gitea_db_pass
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea_db_name
      - POSTGRES_PASSWORD=gitea_db_pass
      - POSTGRES_DB=gitea_db_name
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    secrets:
      - gitea_db_name
      - gitea_db_user
      - gitea_db_pass
