version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=<gitea_name>
      - GITEA__database__USER=<gitea_user>
      - GITEA__database__PASSWD=<gitea_pass>
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2221:22"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=<gitea_user>
      - POSTGRES_PASSWORD=<gitea_pass>
      - POSTGRES_DB=<gitea_name>
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
