version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    hostname: gitea
    env_file:
      - .env
    restart: always
    networks:
      - gitea
      - middle-earth
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:2222"
    depends_on:
      - gitea-postgres

  gitea-postgres:
    container_name: gitea-postgres
    hostname: gitea-postgres
    image: postgres:14
    restart: always
    env_file:
      - .env
    networks:
      - gitea
    volumes:
      - gitea-postgres:/var/lib/postgresql/data

  gitea-runner:
    image: gitea/act_runner:latest
    restart: always
    depends_on:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - gitea
    extra_hosts:
      - <git-domain>:<IP>
      - <registry-domain>:<IP>

networks:
  gitea:
  middle-earth:
    name: middle-earth
    external: true

volumes:
  drone:
  gitea-postgres:
  gitea-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/gitea/data
  gitea-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/gitea/config
